### ISSUE TITLE
Restafval missing

### ISSUE THREAD

**Issue by tjorim** [olibos/HomeAssistant-RecycleApp#1]
I currently only see sensors for GFT, Papier and PMD. Can at least restafval be added as well and/or make it an option in the config flow?

**Comment by olibos** [comment]
Hello @tjorim,

Normally, it should be there:
![image](https://user-images.githubusercontent.com/6031263/201949006-6c05ca29-05bf-4882-98a4-e6b55c999bb0.png)

To diagnose the issue, can you send me the address by mail at olivier.bossaer@gmail.com?
For privacy purpose, you may send me an aproximate street number 😉

**Comment by olibos** [comment]
Thank you @tjorim , 
It seems there are multiple restafval categories and yours was not in my list 😉.

I've added the category and make a new version 1.1.0.
I've tested with the address you provide and now the sensor is shown.

Let me know if it works for you.

**Comment by tjorim** [comment]
Thanks, working great. Needed to delete and add the integration in the process. Now I need to set up a nice card on the dashboard ;)

**Comment by olibos** [comment]
@tjorim Let me know if you found a nice card, I'm stuck with the default entities card for now 😉
