### ISSUE TITLE
Enhancement: Number of days before the next collection

### ISSUE THREAD

**Issue by AdrinkBeer** [olibos/HomeAssistant-RecycleApp#12]
Thanks for your integration ! It's always great to integrate stuffs related to our country.

I was previously using the popular **Garbage Collection** integration for this purpose (https://github.com/bruxy70/Garbage-Collection).

Its entities have an attribute named **Days** to tell the number of days before the next collection.

I know I can create a sensor for this but it would be great if it could be part of the integration itself !

Thanks for your work :)

**Comment by olibos** [comment]
Good idea!

I've made a local test version which sync every night at midnight which compute & store the `days` attribute.
I'll test it for the weekend and keep you posted.

Thank you

**Comment by olibos** [comment]
Hello @AdrinkBeer ,

This feature is in the new release `1.4.0`.
Can you have a look?

Thank you again for your feedback

**Comment by AdrinkBeer** [comment]
Hello,

It looks great so far !
I will check during the month how it behaves for the edge cases :)

Encore merci beaucoup !
