### ISSUE TITLE
Some Collections are missing

### ISSUE THREAD

**Issue by SeibZ-1** [olibos/HomeAssistant-RecycleApp#15]
Hi!
Thanks for this nice integration.

With my address in Quaregnon (post code 7390), I only have two entities : "paper & cardboard" (papier et cartons) and "glass" (verre).

I don't get info or entities about PMC and regular wastes (ordures ménagères).

Thanks

**Comment by PenPenx** [comment]
Un grand merci.

Pour ma part, je n'ai aucune entité
Baudour, CP 7331

thanks you,
For me, no entity :'(
Baudour, CP 7331

**Comment by olibos** [comment]
Bonjour @SeibZ-1 , @PenPenx 

Je viens de vérifier à Quaregnon, la page "guide de tri" renvoi ceci:
![image](https://user-images.githubusercontent.com/6031263/211211905-3fe16be8-3025-4d53-a6a1-0c29d04e895b.png)
Et pour Baudour, c'est encore pire:
![image](https://user-images.githubusercontent.com/6031263/211211998-e3780c61-c53b-47eb-9f8b-5a6f2f0ce5fd.png)


Or, actuellement les collecte sont basées sur les donnés fournies sur cette page.
Je vais devoir changer cette logique!

Je pense faire une nouvelle version en déterminant les collectes sur base du calendrier, ça devrait résoudre les soucis rencontrés.

Merci pour les informations

**Comment by olibos** [comment]
Cette adaptation est dans la version `1.4.0`.
Pouvez-vous mettre à jour, supprimer l'intégration et la recréer.

Elle devrait alors trouver toutes les collectes pour votre adresse.

Pouvez-vous vérifier? 🙂

**Comment by PenPenx** [comment]
Ca fonctionne chez moi.
Merci et belle réactivité ;-)

**Comment by SeibZ-1** [comment]
Je confirme, ça fonctionne aussi chez moi !
Merci beaucoup pour ton boulot et ta réactivité !
