### ISSUE TITLE
Invalid street name

### ISSUE THREAD

**Issue by fanaticDavid** [olibos/HomeAssistant-RecycleApp#21]
Hello,

I just installed v1.5.0 of your custom component but when trying to set it up for my home address, it keeps telling me "Invalid street name". My postal code is 9200 (Sint-Gillis-bij-Dendermonde) and my street name is Heirbaan.
I tried setting it up with my parents' address in 9280 Lebbeke and it worked just fine. My address also works just fine in the Recycle app and on their website.

Any clue as to what could be wrong?

Regards,
David

**Comment by olibos** [comment]
Hello @fanaticDavid ,

I've found the reason 😉.
It's because when you search for "Heirbaan" the api returns 2 addresses:  "Heirbaan" & "Oude Heirbaan".

I'll fix the integration to accept multiple streets results if there is a perfect match.

**Comment by olibos** [comment]
I've pushed a new release: `1.6.0` it should fix your issue

![image](https://user-images.githubusercontent.com/6031263/219956225-f38f74cb-2c25-4f0f-b418-a833ea281b05.png)

Let me know if it works for you.

**Comment by fanaticDavid** [comment]
> I've pushed a new release: `1.6.0` it should fix your issue
> 
> ![image](https://user-images.githubusercontent.com/6031263/219956225-f38f74cb-2c25-4f0f-b418-a833ea281b05.png)
> 
> Let me know if it works for you.

I just installed the update, restarted HA and tried to add my address again. This time, it worked so thank you for the fix!

Just a small detail: it added my address as being in Appels instead of Sint-Gillis-bij-Dendermonde. However, that doesn't seem to matter for the sensors and I manually renamed the integration with the correct town.
