### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by FrodoVB** [olibos/HomeAssistant-RecycleApp#26]
With the previous version I was able to change the date format. Now I can't get it to work. I want to display something like this: 18 April

**Comment by olibos** [comment]
Hello @FrodoVB ,

That's strange because there was no change, that I can remember, about the date mechanisme in this integration.
What was your previous version? To let me check 😉

Have a nice day

**Comment by FrodoVB** [comment]
Hi, 

Thanks for your quick reply.
I'm not really sure what the previous version was...
I do remember that you had to paste a certain code in the configuration.yaml file where you could customize certain things.

**Comment by olibos** [comment]
Oh I think you were using [waste_collection_schedule](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md), which is configured with `configuration.yaml` and offer date formatting.

On my side, the configuration is done with `Config Flow` from the start 😉.
I don't think I can change the sensor behavior without making a breaking change for current users.

Here are some alternatives I can think of:
- Use a custom card which let's you put the format you want to display
- Use a Template Sensor which format the date (sample [here](https://community.home-assistant.io/t/custom-time-and-date-format/280375/2?u=olibos))

Hope it helps

**Comment by FrodoVB** [comment]
Okay, that's where I went wrong...
Thanks for all the information!

**Comment by olibos** [comment]
You're welcome 👍
