### ISSUE TITLE
Initialization fails

### ISSUE THREAD

**Issue by vincentdieltiens** [olibos/HomeAssistant-RecycleApp#27]
Hi,

Initialization fails after entering my adresse (adress is working in !Recycle App).

I get the following error : 

![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/589764/5c84782d-7b8b-4b9f-9881-bbc56130ce9c)

Here is the error from the log : 

> Logger: custom_components.recycle_app.config_flow
Source: custom_components/recycle_app/config_flow.py:61
Integration: RecycleApp (documentation, issues)
First occurred: 15:22:35 (2 occurrences)
Last logged: 15:26:54
>
> Failed to register 'NoneType' object is not subscriptable

HA Version : 

```
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.0
Interface utilisateur : 20230503.3 - latest
```

Don't hesite if you need more informations/context.

Regards,

Vincent

**Comment by vincentjdc** [comment]
After some digging, I found on recycleapp.be endpoint is now : https://api.fostplus.be/recyclecms/app/v1/ instead of https://api.fostplus.be/recycle-public/app/v1/

**Comment by olibos** [comment]
Thank you @vincentjdc !

I'll check this weekend and make a release 😉

**Comment by olibos** [comment]
Hello @vincentdieltiens ,

It should be fixed in v2.0.0.
Can you have a look?

**Comment by vincentdieltiens** [comment]
I'll check that this week 😉

**Comment by vincentdieltiens** [comment]
I've done the update. Works like a charm,👌
