### ISSUE TITLE
can not install recycle app

### ISSUE THREAD

**Issue by wvdb0** [olibos/HomeAssistant-RecycleApp#28]
i get the error: Fout tijdens initialisatie, probeer het opnieuw when I give in all the fields. it was ok before.

**Comment by wvdb0** [comment]
thanks!

**Comment by olibos** [comment]
It's fixed in v2.0.0
Can you check if it works on your side after the update?

**Comment by wvdb0** [comment]
Top. Works as expected
----- Oorspronkelijk bericht -----
Van: Olivier Bossaer ***@***.***>
Aan: olibos/HomeAssistant-RecycleApp ***@***.***>
Cc: wvdb0 ***@***.***>, Author ***@***.***>
Verzonden: Sun, 14 May 2023 16:45:25 +0200 (CEST)
Onderwerp: Re: [olibos/HomeAssistant-RecycleApp] can not install recycle app (Issue #28)

It's fixed in v2.0.0
Can you check if it works on your side after the update?
