### ISSUE TITLE
How you install this

### ISSUE THREAD

**Issue by verhoevendanny** [olibos/HomeAssistant-RecycleApp#3]
Hello Olivier

I installed your repository via HACS into my homeassistent.
But what is thé next step? Somewhere you should specify my home adres.... Bug you do not mention where.
When adding this repository no configuration-questions where asked.
So what do i have to do?
Thx

**Comment by olibos** [comment]
Hello @verhoevendanny ,

You're right, I'll adapt the documentation with a more step by step usage.
Normally, it's a 3 steps process:
* Install the HACS repository:
[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=olibos&repository=HomeAssistant-RecycleApp)
* Install the integration:
[![Open your Home Assistant instance and start setting up a new integration.](https://my.home-assistant.io/badges/config_flow_start.svg)](https://my.home-assistant.io/redirect/config_flow_start/?domain=recycle_app)
* Complete the confiuration process:
![image](https://user-images.githubusercontent.com/6031263/210235247-a685013c-5dc9-49c5-a8a0-372d08a215fb.png)

Can you test it and tell me if it works for you?

Based on you're feedback I'll adapation the documentiont 😉

Have a nice day

**Comment by verhoevendanny** [comment]
Hello Olivier

The second link is indeed the one that started the config.

Only sensor.glas is missing!

Grts
Danny

Op ma 2 jan. 2023 14:07 schreef Olivier Bossaer ***@***.***>:

**Comment by olibos** [comment]
Thank you for your feedback!

Is it a collect like the others?
Can you send me an approximate address to let me check in recycle app how it's managed? With ideally the next collection day.
You may send it to my mail address to avoid private data leak (olivier.bossaer@gmail.com)

**Comment by PatrickGlesner** [comment]
Hello,

For me, it woks fine!

Thanks a lot,
Patrick.

**Comment by olibos** [comment]
I've updated the documentation, can you have a look on the draft:
https://github.com/olibos/HomeAssistant-RecycleApp/blob/feature/enhance_documentation/README.md

Do you have any remarks?

**Comment by PatrickGlesner** [comment]
Perfect!

Best regards,
Patrick.

**Comment by olibos** [comment]
Thank you @PatrickGlesner , I'll close the documentation part and have created a new issue for glass collection in gent #8
