### ISSUE TITLE
icon colours

### ISSUE THREAD

**Issue by geertvercamer** [olibos/HomeAssistant-RecycleApp#30]
Hi, 

the icons are almost invisible on a dark theme, ie. noctis gray dark.

Would be nice to have light-coloured icons too.

Thanks

**Comment by olibos** [comment]
Hello @geertvercamer ,

Thank you for your feedback, I'll check what's possible to get better icons for dark themes.

Thank you

**Comment by olibos** [comment]
I've install Noctis Grey Dark, but I don't seer the issue:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/dc303bb9-63f9-4296-b5e8-a3dea74458ef)

Can you send me a screenshot from your side? And maybe suggest an alternative?

**Comment by geertvercamer** [comment]
Hi,

my mistake obviously. The problem was with another integration. Sorry about
that.

Is there a way to format the date?
Thanks

Geert

**Comment by olibos** [comment]
Hello @geertvercamer ,

There is no builtin way to customize the date format.
But it's doable with template sensors or tools like: https://github.com/thomasloven/lovelace-template-entity-row

Hope it helps,

Olivier
