### ISSUE TITLE
Missing "Green waste"

### ISSUE THREAD

**Issue by Jhamende** [olibos/HomeAssistant-RecycleApp#31]
Hello, 

This integration is working very well. I'm just missing green waste in my case. 
Don't know if someone else is missing it too ? 

Kind regards,

**Comment by olibos** [comment]
Hello,

Can you give me an address to check?

Olivier

**Comment by Jhamende** [comment]
Hello, 

Please check Try à Fourche 1, 1430 Rebecq. 
Through the Recycle App I have green waste showing up. 

I have a friend who uses your integration too in Flanders and he has green waste.  

Thank you

**Comment by olibos** [comment]
Thank you,

It will be added in next release:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/dad78dfc-db48-460d-a1eb-21ba4c8f1f24)

**Comment by Jhamende** [comment]
Thank you!

**Comment by olibos** [comment]
The new release is available.

- Update in HACS
- Reload HA
- Go to Settings > Devices & Services.
- Search for RecycleApp click on the entry
- Click on configure & Submit 

You should be good 🤞

Have a nice day,

Olivier
