### ISSUE TITLE
Issue with integration

### ISSUE THREAD

**Issue by Devairen** [olibos/HomeAssistant-RecycleApp#33]
I’m a complete noob regarding coding so please correct me if I’m doing something wrong, but after adding this in HACS and as an integration, I configure my address (which works) and then have no idea how to proceed.

No devices show up in HA, nor any entities..

I’ve removed the config with my address and set a new one by adding a device, and still nothing shows up.

**Comment by olibos** [comment]
Hello @Devairen ,

Can you give me an address to let me check?

Thank you

**Comment by Devairen** [comment]
Hey Olivier,

You mean physical address to run the data pull?

It's Corneel Vermijlenlaan 50, 2100 Deurne

Kind regards - Groetjes,
Joris
________________________________
Van: Olivier Bossaer ***@***.***>
Verzonden: Saturday, August 12, 2023 6:00:51 PM
Aan: olibos/HomeAssistant-RecycleApp ***@***.***>
CC: Devairen ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [olibos/HomeAssistant-RecycleApp] Issue with integration (Issue #33)


Hello @Devairen<https://github.com/Devairen> ,

Can you give me an address to let me check?

Thank you

**Comment by olibos** [comment]
Hello @Devairen ,

Sorry for the delay.
I've check at your address with:
https://www.recycleapp.be/calendar

And there is no information returns :
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/cfd18b30-c508-4836-85a1-8c5d5640e105)

As their web API is not returning any information, there is no data in my integration.
Maybe, you can contact them https://www.recycleapp.be/contact to know why?

When their websites returns information for your address, you may refresh this integration to show the correct data.

Sorry for the inconvenience,

Olivier
