### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by RafSchandevyl** [olibos/HomeAssistant-RecycleApp#35]
Hi,

Would it be possible to change data format to DD-MM-YYYY.  
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/78409275/f3615624-bfb5-43d0-86df-bae684ae43c3)

but on my phone i can only see the year.  
Regards

**Comment by olibos** [comment]
Hello @RafSchandevyl ,

I'll check what's doable to change the display value without changing the sensor type.

I'm just waiting the end of the heat wave 😉

Have a nice weekend

**Comment by olibos** [comment]
Hello @RafSchandevyl ,

After update the integration to v2.2.0, you'll have an option in the `configure` screen to change the date format:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/7eec3a92-4d72-4908-aa15-72aec30446fc)
The formatting is based on [Python date formatting](https://docs.python.org/3/library/datetime.html#format-codes)
