### ISSUE TITLE
Feature request "next pickup" 

### ISSUE THREAD

**Issue by Jhamende** [olibos/HomeAssistant-RecycleApp#37]
Hello,

Would it be possible to add an entity called "next pickup" with the nearest pickup only? Well that would be great, like this we can add a card with only 1 entity instead of all entities without struggling a lot with custom entities and conditional cards. 

Kind regards,

**Comment by olibos** [comment]
Hi @Jhamende,

Thanks for the suggestion.
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/60a08a54-57db-43ab-b42a-906f6674e8fd)

If I understand your idea correctly, it should add a new sensor: "Next Pickup" with the name "Sac Noir" and value of 03/10.
But after October 3, I'm not sure what to do because "Sac bleu", "Carton" and "Jardin" have the same date.

Any ideas?

**Comment by Jhamende** [comment]
Hello, 

I didn't think about the possibility to have 2 pickups the same day, and I understand it makes things a bit more complicated. 
Other solution is indeed to add additional helpi,g sensors like the one I made:

Example: 
===========================
  - platform: template
    sensors:
        date_demain:
           friendly_name: date demain
           value_template: "{{ (as_timestamp(now())+(86400)) | timestamp_custom('%Y-%m-%d') }}"

  - platform: template
    sensors: 
        pmc_demain:
           friendly_name: pmc demain
           value_template: "{% if states('sensor.pmc') == states('sensor.date_demain') -%}True{%- else -%}False{%- endif %}"
===========================

So in my case I made a sensor with date of tomorrow. When pickup PMC is tomorrow, then value is true for pmc_demain, else it will be false. 

In my yaml I added a conditional card, if pickup PMC is tomorrow, then show up card, else hide it. 

If these sensors for each pickup type is delivered with the plugin, it would help users gain time to add possibility to trigger some sensors for automations like notifications etc. 

I hope you understand everything I wrote up here :)

Kind regards
Jonathan

**Comment by olibos** [comment]
If I have to solve the same problem, I think of 2 simple ways to do that:
With an `entity-filter` card:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/2aebced8-696d-4ad1-81b6-11d3294f47c9)

Or if you prefer templates:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/ad52b628-1625-453d-b8a8-bdae52d1daab)

Boths scenarios use the "days" attribute available on each sensor.

What do you think?

**Comment by Jhamende** [comment]
Thanks a lot for your answers. 
Well indeed first scenario is good for entity-filter card, but there are not sorted from first to latest. 

Templating seems quite good for making automations. 
could these templates be delivered with plugin or should I make them my self ? 

Kind regards,

**Comment by MathiasVandePol** [comment]
> Hi, Is there a simple way to make notifications one day before the pickup?
> 
> Kind regards and thanks for the integration

I created something like this with the following helpers and automations. I only use `PMD, Papier-Karton and Restafval` so you might have to adapt

#### Helpers

*Tomorrow Date*
```yaml
{{ (as_timestamp(now())+(86400)) | timestamp_custom('%Y-%m-%d') }}
```
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/606681/d2c5cbdb-0731-406b-9426-39c9f29e2209)

*Tomorrow's Pickup(s)*
```yaml
{% if states('sensor.papier_karton') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.papier_karton', 'friendly_name') +  " - " }}
{%- endif %}
{%- if states('sensor.pmd') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.pmd', 'friendly_name')  +  " - " }}
{%- endif %}
{%- if states('sensor.restafval') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.restafval', 'friendly_name') +  " - " }}
{%- endif %}
```
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/606681/c2535e04-c7fd-461f-86a7-528a3ef1da35)

#### Automation:
```yaml
alias: Afval ophalen
description: ""
trigger:
  - platform: time
    at: "19:00:00"
condition:
  - condition: template
    value_template: >-
      {% if is_state('sensor.tomorrow_s_pickup_s', '') %}false{% else %}true{%
      endif %}
action:
  - service: notify.mobile_app_pixel6a
    metadata: {}
    data:
      message: Morgen afval ophaling van {{states('sensor.tomorrow_s_pickup_s')}}
mode: single

```

**Comment by olibos** [comment]
Thanks @MathiasVandePol

If it's ok for you I can add your configuration and samples in the documentation.

**Comment by MathiasVandePol** [comment]
> Thanks @MathiasVandePol
> 
> If it's ok for you I can add your configuration and samples in the documentation.

Yes of course 👍

**Comment by Yakie996** [comment]
Hi, I implemented the autmoation and the helpers, tomorrow they will collect 'snoeihout' I added it to the template, but the automation gives 'condition not met'. maybe it has something to do with the dates not metching of tomorrow's date and from snoeihout. 

{% if states('sensor.papier_karton') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.papier_karton', 'friendly_name') +  " - " }}
{%- endif %}
{%- if states('sensor.pmd') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.pmd', 'friendly_name')  +  " - " }}
{%- endif %}
{%- if states('sensor.restafval') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.restafval', 'friendly_name') +  " - " }}
{%- endif %}
{%- if states('sensor.gft') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.gft', 'friendly_name') +  " - " }}
{%- endif %}
{%- if states('sensor.glas') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.glas', 'friendly_name') +  " - " }}
{%- endif %}
{%- if states('sensor.snoeihout') == states('sensor.tomorrow_date') -%}
{{ state_attr('sensor.snoeihout', 'friendly_name') +  " - " }}
{%- endif %}

![Screenshot_20240118_190455_Home Assistant](https://github.com/olibos/HomeAssistant-RecycleApp/assets/19747119/838a89be-edcb-46a4-a535-23ac3a833b0b)
![Screenshot_20240118_190555_Home Assistant](https://github.com/olibos/HomeAssistant-RecycleApp/assets/19747119/dc7563fe-925a-49ce-bacc-bef2640e03c2)
![Screenshot_20240118_190534_Home Assistant](https://github.com/olibos/HomeAssistant-RecycleApp/assets/19747119/1c18cf7f-4235-4225-853b-3b5545d40cbf)
![Screenshot_20240118_190515_Home Assistant](https://github.com/olibos/HomeAssistant-RecycleApp/assets/19747119/7c264b50-02b9-4a61-975d-dcd48d174a57)

**Comment by olibos** [comment]
Hello @Yakie996,

the reason is linked to the choosed date format.
Your template compares: `2024-01-19` with `19-01` which are differents.
I think, it's simpler to use the days attribute like in this [addapted sample](https://github.com/olibos/HomeAssistant-RecycleApp/?tab=readme-ov-file#template-helper) 
```jinja
{% set tomorrow_pickups = namespace(entities=[]) %}
{% set collect_types = ['sensor.dechets_non_recyclables_sac', 'sensor.pmc', 'sensor.papier'] %}
{% for collect_type in collect_types %}
  {% if state_attr(collect_type, 'days') == 1 %}
    {% set tomorrow_pickups.entities = tomorrow_pickups.entities + [state_attr(collect_type, 'friendly_name')] %}
  {% endif %}
{% endfor %}
{{ tomorrow_pickups.entities | join(' - ') }}
```

Let me know if it works for you.

I hope the [next release](https://github.com/olibos/HomeAssistant-RecycleApp/issues/41) will make those kinds of automation more easier!
