### ISSUE TITLE
Feature request - add Recycle park opening hours

### ISSUE THREAD

**Issue by dietersar** [olibos/HomeAssistant-RecycleApp#39]
Please add the opening hours for the Recycle park.

This is visible in the (Android) Recycle! app beneith the general waste collections

**Comment by olibos** [comment]
Hello @dietersar , it's definetly a nice addition.
I'll check what is required to implement it.

**Comment by olibos** [comment]
Hello @dietersar ,

Here is my proposal, I'll add a new "service" with the name/address of the recycle park.
In it there will be 7 text sensors, one for each days with the opening hours.
And a Calendar sensor with those opening hours like the feature I'm working on #41 Collect Calendar

What do you think?

**Comment by dietersar** [comment]
sounds good to me :-)

**Comment by olibos** [comment]
Hello @dietersar ,

I've pushed a new pre-release: v2.3.0-b1
This release adds the recyparks and collect calendars.

Can you test this version?
After update & restart home assistant, go to the device page & click CONFIGURE:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/a77c1595-ee10-430a-9d19-32d801a637ba)

complete the form:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/e6de74f0-633f-4a71-a146-0fb6ddb2727b)

and select all the recycling parks you want to add:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/2991007b-1c3e-40aa-a8e1-49a888a07722)

**Comment by dietersar** [comment]
works perfectly, thx!

![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/25160084/27ce3725-b966-4ee4-b7fb-be2a292f68dd)
