### ISSUE TITLE
sensor "textiel" missing

### ISSUE THREAD

**Issue by ad2381** [olibos/HomeAssistant-RecycleApp#51]
Hi olibos,
Since the beginning of this year our local wastecollector (IOK) is also collecting textile. Can you please add the sensor so it can be used?

https://www.iok.be/textiel

Thanks and congrats with all the work done.

**Comment by olibos** [comment]
Hello @ad2381 ,
Is this information also shown on https://www.recycleapp.be/dashboard?
If yes can you send me an (aproximative) address so I can find the information returned by the API.

Thank you,

Olivier

**Comment by ad2381** [comment]
Hi Olivier, yes the info is visible in the dasboard. You van use
ZIP: 2380
City: Ravels
Street: Grote Baan
Number: 100

**Comment by olibos** [comment]
It will be short for tomorrow 😉
But it should be implement for next collect 👍️

**Comment by olibos** [comment]
It's available in [v2.3.0-b4](https://github.com/olibos/HomeAssistant-RecycleApp/releases/tag/v2.3.0-b4) 
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/83b82bda-5b49-4755-945b-b55ab3e5a892)


![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/7a89c781-75dd-46b7-8830-bb83c6754977)

Let me know if it works for you

**Comment by ad2381** [comment]
Hi Olivier b4 is working and the "textiel" sensor is now also visible. I see that you also added the opening hours of the recycling park in the neighborhood and that it is possible the select the nearest one. GREAT JOB
One more question: although my localization is set to Belgium and language dutch, the names of the weekdays are in English when I use %A %d %B

**Comment by olibos** [comment]
Thank you @ad2381 ,

I don't know why those names are in English.
I'll try to have a look if there a quick fix 😉
