### ISSUE TITLE
TIMESTAMP instead of DATE device class?

### ISSUE THREAD

**Issue by Friedrieck** [olibos/HomeAssistant-RecycleApp#54]
Could you please consider changing or adding the option to have the device class as timestamp instead of date?
It allows to have the UI taking care of nicely displaying a relative time (and the date still available in the more-info dialog):
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/12567014/9952b9cf-3f93-404c-8431-aa5879caaea3)

**Comment by olibos** [comment]
Hello @Friedrieck ,

Thank you for your feedback 👍

I'll check how it can be done without creating a breaking change.

**Comment by olibos** [comment]
Hello @Friedrieck this will be added in release 2.4.0.
To use timestamp simply go to the "device/service" configuration page and update the date format to TIMESTAMP.
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/9c9ba3ce-17c5-4ad2-82fe-99d52ac2775e)

Result:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/33ab5e76-a835-49fd-8eca-a0fc0d888cc6)

**Comment by Friedrieck** [comment]
Great, I'll test once released!

**Comment by Friedrieck** [comment]
It works as expected, many thanks!

**Comment by olibos** [comment]
You're welcome.

Have a nice weekend

**Comment by wjansenw** [comment]
tnx, i was checking how I could achieve this some time ago, but glad I see this is now implemented!
