### ISSUE TITLE
State not vissible from helper

### ISSUE THREAD

**Issue by Jeronimo1971** [olibos/HomeAssistant-RecycleApp#56]
Did a copy paste of your code for the helper. But i recieve no state: true or false? Nothing listed

![Scherm­afbeelding 2024-02-13 om 18 04 22](https://github.com/olibos/HomeAssistant-RecycleApp/assets/55802752/c5b2cd7b-fa9c-428b-888d-f119e083e707)
![Scherm­afbeelding 2024-02-13 om 18 03 34](https://github.com/olibos/HomeAssistant-RecycleApp/assets/55802752/3bba4eee-3de7-498b-b620-68e9bfe3aa5c)

**Comment by olibos** [comment]
Hello @Jeronimo1971 ,

Have you updated the second line with your sensors IDs?

**Comment by Jeronimo1971** [comment]
Yes, just put 1 sensor in it… sensor.gft.
But nothing changed.
But even when I put the wrong sensor in it, I should get the state: false… no?


Op 13 feb 2024, om 21:58 heeft Olivier Bossaer ***@***.***> het volgende geschreven:


Hello @Jeronimo1971 <https://github.com/Jeronimo1971> ,

Have you updated the second line with your sensors IDs?

**Comment by Jeronimo1971** [comment]
Ps thx for investigating it !! :-)

**Comment by Jeronimo1971** [comment]
My config:
{% set tomorrow_pickups = namespace(entities=[]) %}
{% set collect_types = ['sensor.gft'] %}
{% for collect_type in collect_types %}
  {% if state_attr(collect_type, 'days') == 1 %}
    {% set tomorrow_pickups.entities = tomorrow_pickups.entities + [state_attr(collect_type, 'friendly_name')] %}
  {% endif %}
{% endfor %}
{{ tomorrow_pickups.entities |join(' - ') }}

**Comment by olibos** [comment]
Sorry, I misunderstood your question.
This template does not return true or false if there is a collection tomorrow.
It lists all the collections for tomorrow. So if it's empty, that means there's no collection = false.
If you have paper and PMD tomorrow, it will return "Paper - PMD".

**Comment by Jeronimo1971** [comment]
No problem, FYI... script modified to below.
This way I get a result 1 or 0, which I can use again for a conditional card. (I set this to 2 days, but it can be adjusted).
Thanks for the recycling app, it is a nice one :-)

{% set has_date_glas = false %}
{% set has_date_gft = false %}
{% set has_date_papier_karton = false %}
{% set has_date_pmd = false %}
{% set has_date_restfractie = false %}

{% set days_attr_glas = state_attr('sensor.glas', 'days') %}
{% if days_attr_glas != 'unavailable' %}
    {% set has_date_glas = days_attr_glas | int <= 2 %}
{% endif %}

{% set days_attr_gft = state_attr('sensor.gft', 'days') %}
{% if days_attr_gft != 'unavailable' %}
    {% set has_date_gft = days_attr_gft | int <= 2 %}
{% endif %}

{% set days_attr_papier_karton = state_attr('sensor.papier_karton', 'days') %}
{% if days_attr_papier_karton != 'unavailable' %}
    {% set has_date_papier_karton = days_attr_papier_karton | int <= 2 %}
{% endif %}

{% set days_attr_pmd = state_attr('sensor.pmd', 'days') %}
{% if days_attr_pmd != 'unavailable' %}
    {% set has_date_pmd = days_attr_pmd | int <= 2 %}
{% endif %}

{% set days_attr_restfractie = state_attr('sensor.restfractie', 'days') %}
{% if days_attr_restfractie != 'unavailable' %}
    {% set has_date_restfractie = days_attr_restfractie | int <= 2 %}
{% endif %}

{{ 1 if has_date_glas or has_date_gft or has_date_papier_karton or has_date_pmd or has_date_restfractie else 0 }}
