### ISSUE TITLE
ILVA - missing city?

### ISSUE THREAD

**Issue by MarcEngrie** [olibos/HomeAssistant-RecycleApp#62]
Hi,

Installed RecycleApp in Home Assistant and configured it according to my situation. So I am living in Geraardsbergen in Belgium and entered postal code 9500. Based on that, it gives me the correct list of related recycle parks but when I want to choose 'Geraardsbergen' from thie list, it is not in the list. The list only contains: Aalst 1, Aalst 2 (Hofstade), Affligem, Denderleeuw, Galmaarden, Herzele, Ninove, Oosterzele, Sint-Lievens-Houtem and Zottegem. 

Any reason why 'Geraardsbergen' is not showing in the list eventhough it is part of the ILVA-group? 

Regards
Marc Engrie
![Screenshot 2024-03-19 202157](https://github.com/olibos/HomeAssistant-RecycleApp/assets/19575705/fbe64106-614a-4f6e-9441-df8c5ca874d3)

**Comment by olibos** [comment]
Hello @MarcEngrie ,

I've found the reason why it's not showing in the list.

It's because the API request for container parks takes only the first 10. I was thinking it should be enough but not in your case 😉

I'll make an update next week.

**Comment by olibos** [comment]
Greetings @MarcEngrie,

A fresh beta release "v2.5.0-b1" has been deployed. This update is intended to address the problem you've encountered. Could you please verify its resolution on your end?

[Your Name]![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/6031263/3a03301d-ce79-41e3-943b-5ab4e15580a7)

Thank you
