### ISSUE TITLE
Adding integration results in error

### ISSUE THREAD

**Issue by RobinAstle** [olibos/HomeAssistant-RecycleApp#65]
HA version:
Core 2024.4.0
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240403.1

Trying to add the recycle app results in error:
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

**Comment by olibos** [comment]
Hello @RobinAstle 

I'm sorry to hear that you're encountering this issue. To help me understand the problem better, could you please provide the following logs?

- Home Assistant logs (found in `Configuration > Logs`)
- Any error messages that appear in the Home Assistant frontend

Thank you for bringing this to my attention, and I look forward to resolving it for you.

**Comment by RobinAstle** [comment]
Frontend error:
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/3233861/5895232b-aa8c-44d5-9edb-58b887ffe8fe)
Unfortunately the log does not show anything related to HACS or this addon in particular.
I'm new to HA, maybe I can increase the log level somewhere?

**Comment by RobinAstle** [comment]
Update, on desktop (MS edge browser) I only see 
![image](https://github.com/olibos/HomeAssistant-RecycleApp/assets/3233861/ab24013c-1939-426e-b223-64bea0a47b47)

On mobile however I see the download button in the right bottom corner... which does complete in a successful installation.
This might not be related to the addon itself I think, do I need something more configured to benefit from some kind of git integration or does it not work differently from the download and install option?

**Comment by olibos** [comment]
Great to hear that you've unblocked yourself 😄.

I've tried on my side the click on the Add Integration from my github and seems to work.
Normally the only requirement are to have :
- HACS installed
- Installed the Recylce App integration from HACS

and then click the add integration button or directly add the integration from you HA instance.

Thank you for your feedback.
