### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [olibos/HomeAssistant-RecycleApp#7]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by olibos** [comment]
Hello @frenck ,

I'll change that with the next release.

Thank you for your feedback

**Comment by olibos** [comment]
Hello @frenck ,

Is there any linting tool from Home Assistant which checks such kind of depreciations?
Or a Github action to validate the code ?

Thank you again for your input 🙂

**Comment by frenck** [comment]
👋 @olibos,

We have "some" tooling, but not too many (as our primary goal, in general, is maintaining Core itself, of course). We do list changes in the release notes (dev changes, underneath the breaking changes section each release).

And we publish blog articles on technical changes for developers on our dev blog:

https://developers.home-assistant.io

Anyways, thanks for the migration!

Oh! And a Happy New Year 🥂 

../Frenck

**Comment by olibos** [comment]
Thank you!

I'll check those resources.

And happy new year to you too 🥂🍾🎉
