### ISSUE TITLE
How to use the date format relatively?

### ISSUE THREAD

**Issue by Devairen** [olibos/HomeAssistant-RecycleApp#72]
Hello,

First of all, thanks for this integration, as someone with next to no coding knowledge this saved my life, inputting this data into home assistant is very nice.

You mention on the github page that it is possible to format the date relatively, to have the PMD sensor display: "in 2 days", instead of date/month/year. How do I do this? I've looked into the python date/time formatting but am at a complete loss, and also cannot find anything about the innate HA time templates you mentioned..

I tried a workaround creating template sensors which do the correct thing (see example), but in this case I lose the nice looking custom icons, which I definitely want to use, as otherwise I'd have to come up with custom icons somehow.

Example of my current format on the first row, and using template sensors on the second row, I'd like the timestamps combined with the icons:
![image](https://github.com/user-attachments/assets/0c2aa93f-52c8-45f3-bf19-97172fadb20c)

Thanks in advance!
Kind regards,
Joris

**Comment by Devairen** [comment]
Hello Olivier,

Sadly not, I figured this is what you meant initially, but Home Assistant doesn't seem to process this timestamp date correctly into relative time..

https://jmp.sh/pBBjw5tl

I've deleted and reconfigured just to make sure, and the same behavior stays.

**Comment by olibos** [comment]
In the sensor details, it's the full date even if on the dashboard it should display the relative date.
![image](https://github.com/user-attachments/assets/2af6d395-084f-4102-abf7-be0eb42fdf98)

It's maybe linked to the custom card you use.
I've tried with buit-in "entities" and "tile" cards and both shows relative dates
![image](https://github.com/user-attachments/assets/ed1ed30e-06d2-434b-b99b-fadbc600a174)

Which card do you use?

**Comment by Devairen** [comment]
Hello Olivier,

You're absolutely right, it's the cards that are messing me up! If I throw it in a standard 'entities' card or a mushroom card it shows correctly:

![image](https://github.com/user-attachments/assets/ae7bdc01-0548-49be-bb60-ca9d7d08b2c3)

This specific card is a custom bubble card (button type, specifically).

Thanks for your support!
Cheers,
Joris

**Comment by olibos** [comment]
Thanks for the feedback
