### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by svenbw** [olibos/HomeAssistant-RecycleApp#77]
When I add the integration to HA and fill out my address data the exception below occurs when I press the submit button.
```
2024-09-04 12:49:26.137 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.12/asyncio/futures.py:381 (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/futures.py", line 383, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.12/asyncio/futures.py", line 359, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```
The same error occurs every time I add the integration, network is OK, [settings.json ](https://www.recycleapp.be/config/app.settings.json) can be reached (from browser).

HA core is at 2024.8.3

**Comment by jeroendw88** [comment]
Hi, I have the same since 3hs or so.

**Comment by svenbw** [comment]
Thanks for looking into this.

Tested with:
- Private address
- Heuvelstraat 91, 2530 Boechout (Gemeentehuis)
- Paradeplein 2, 2500 Lier (Stadhuis)
- Stadsplein 2, 2640 Mortsel (Stadhuis)

**Comment by thomasddn** [comment]
Similar issue on my end. After restarting HA (because I updated HACS to v2.0.1), the integration won't load anymore.

```
2024-09-04 15:31:00.049 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry {MY ADDRESS} for recycle_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/recycle_app/__init__.py", line 101, in async_setup_entry
    await async_refresh()
  File "/config/custom_components/recycle_app/__init__.py", line 95, in async_refresh
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/recycle_app/__init__.py", line 61, in async_update_collections
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by olibos** [comment]
> Thanks for looking into this.
> 
> Tested with:
> 
> * Private address
> * Heuvelstraat 91, 2530 Boechout (Gemeentehuis)
> * Paradeplein 2, 2500 Lier (Stadhuis)
> * Stadsplein 2, 2640 Mortsel (Stadhuis)
> 
> /Edit: If I need to add some logging in the code, to further investigate please let me know

I've tested on my side with : Heuvelstraat 91, 2530 Boechout (Gemeentehuis)
![image](https://github.com/user-attachments/assets/d31ba133-0e43-47de-ad72-48ad496308d9)



> Similar issue on my end. After restarting HA (because I updated HACS to v2.0.1), the integration won't load anymore. HA version is 2024.8.1.

I've HACS in 2.0.0 on my install.
I'll setup a dev version with latests versions and keep you posted.

**Comment by BELTFD** [comment]
Similar issue on my end too. Issue detected after restarting HA following HACS Upgrade from V2.0.0 to v2.0.1, the integration won't load anymore. HA version is 2024.8.3 on HAGreen.

**Comment by svenbw** [comment]
As always it works on the developers system, probably the software taking revenge for past bugs :-)

> I've HACS in 2.0.0 on my install.
> I'll setup a dev version with latests versions and keep you posted.

I'm on 2024.8.3 of HA, HACS was 2.0.0, upgraded HACS to the latest version but the exception still occurs.

**Comment by IetIesAai** [comment]
Hass 2024.9, hacs 2.0.1, same issue, also an address in Flanders....

**Comment by LioBoul** [comment]
Same problem after updating HACS 🙁

**Comment by jodewee** [comment]
Same over here, broken since new hacs

**Comment by jeroendw88** [comment]
I'm still on the old Hacs and for me its also broken but I also had to restart home assistant today and since then it was broken. Core 2024.8.3

**Comment by jodewee** [comment]
maybe since the core 2024.8.3?
i did the upgrade of hacs & the core at the same moment.
![image](https://github.com/user-attachments/assets/49dab23a-e85f-4d8b-bb69-cc693c1acff3)

**Comment by Pastaloverzzz** [comment]
> maybe since the core 2024.8.3? i did the upgrade of hacs & the core at the same moment. ![image](https://private-user-images.githubusercontent.com/40162805/364521557-49dab23a-e85f-4d8b-bb69-cc693c1acff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NzkwMjksIm5iZiI6MTcyNTQ3ODcyOSwicGF0aCI6Ii80MDE2MjgwNS8zNjQ1MjE1NTctNDlkYWIyM2EtZTg1Zi00ZDhiLWJiNjktY2M2OTNjMWFjZmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE5Mzg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNzhjZTlkZGNlODc1MzU3NzNlNDNjNGFmMTE3MzZhYmVjMDg5MDYyOGIxMmE0MjY2ODY2MTRlYTg0OTgwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzD-MAADgdLDAZyc3dRpwdWbC3xCpZ19Q1vPy4MiHD8)

I don't think Core 2024.8.3 is the problem, i already updated the core to 2024.8.3 some time ago and never had issues until today after installing 2024.9.0+HACS 2.0.1

**Comment by jodewee** [comment]
already tried: remove integration, reboot & re-add under core 2024.9 + new hacs --> does not solve the issue

**Comment by svenbw** [comment]
Thanks!

**Comment by olibos** [comment]
The problem was not linked to HACS nor HA version but a change in FostPlus API.
I've pushed a new version: [v2.5.2](https://github.com/olibos/HomeAssistant-RecycleApp/releases/tag/v2.5.2)

Let me know if it works for you.
Thanks for all the details submitted.

**Comment by LioBoul** [comment]
> The problem was not linked to HACS nor HA version but a change in FostPlus API. I've pushed a new version: [v2.5.2](https://github.com/olibos/HomeAssistant-RecycleApp/releases/tag/v2.5.2)
> 
> Let me know if it works for you. Thanks for all the details submitted.

It's OK for me 🥳

**Comment by Pastaloverzzz** [comment]
Yes, this fixed it for me as well. Thanks!! 🤗🙏

**Comment by svenbw** [comment]
Fixed!

**Comment by jodewee** [comment]
many thanks for the fix! awesome integration ;-)
