### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by groofyke** [olibos/HomeAssistant-RecycleApp#79]
I can't install the integration (yes, I do have HACS).
When I click on "Add integration" from this page (http://homeassistant.local:8123/hacs/repository/562404203), it asks to open the page in Home Assistant. After clicking "open link", it moves to my Home Assistant and then I get the following error : 

> This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

I have the following HA versions installed:
Core2024.9.1
Supervisor2024.08.0
Operating System13.1
Frontend20240906.0

**Comment by olibos** [comment]
Hello @groofyke,

Thank you for your message. Can you confirm that you've done the following:
1. Install the Integration in HACS: Make sure you have added the integration through HACS.
1. Restart Home Assistant: After installation, restart Home Assistant to ensure the integration is properly loaded.
1. Add the Integration: Go to "Settings > Devices & Services" in the Home Assistant UI. Click on the "+ Add Integration" button at the bottom right, and you should be able to find and configure the integration from there.
![image](https://github.com/user-attachments/assets/f15e86b7-e44c-41ce-85a7-8c4152f771af)

**Comment by groofyke** [comment]
Thanks for your reply. 
step 1 and 2, I confirm this is completed
step 3 : “recycleapp” can’t be found when searching. 
FYI : I do see the “recollect waste” integration that is visible in your screenshot.

**Comment by olibos** [comment]
Can you go to: http://homeassistant.local:8123/config/devices/dashboard
and search for "recycle" to check if "RecycleApp" is correctly listed:
![image](https://github.com/user-attachments/assets/7e088c20-2a24-457a-9c4f-971b339b41bc)

**Comment by olibos** [comment]
You're right, the documentation is still a bit out of date / unclear.

I'll try to fix that 😉

I hope, that you'll find this integration helpfull!
